spring:
  profiles:
    active: dev

---

spring.config.activate.on-profile: dev
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 612425wsl
mybatis:
  configuration:
    map-underscore-to-camel-case: true